In [1]:
import numpy as np

a = np.array([[10,20,30,40],[50,60,70,80]])

a


array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [4]:
a.shape

(2, 4)

In [5]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]]) 

In [6]:
d.shape

(2, 3, 4)

In [7]:
d.ndim

3

In [8]:
d * 2

array([[[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]],

       [[22, 24, 26, 28],
        [30, 32, 34, 36],
        [38, 40, 42, 44]]])

In [9]:
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [11]:
d[0][0] * 2

array([2, 4, 6, 8])

````
연습 문제 3.2.1

지금까지 공부한 명령어를 사용하여 다음과 같은 배열을 만들어라.

```
array([[   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [  10.,   20.,   30.,   40.,   50.],
       [  60.,   70.,   80.,   90.,  100.],
       [ 110.,  120.,  130.,  140.,  150.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [  10.,   20.,   30.,   40.,   50.],
       [  60.,   70.,   80.,   90.,  100.],
       [ 110.,  120.,  130.,  140.,  150.]])
```
````

In [12]:
a = np.zeros((3,3))
b = np.ones((3,2))
c = np.arange(10,51,10)
d = np.arange(60,101,10)
e = np.arange(110, 151,10)

f = np.hstack([a,b])

g = np.vstack([f,c,d,e])
h = np.vstack([g,g])
h


array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [17]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

In [15]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [18]:
z = x + y

In [19]:
z

array([10002, 10004, 10006, ..., 29996, 29998, 30000])

In [22]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 4, 3])
np.all(a == c)



False

In [23]:
x = np.vstack([range(7)[i:i + 3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [26]:
y = np.arange(7)
y.reshape(5,3)

ValueError: cannot reshape array of size 7 into shape (5,3)