In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
text = [
    "a better tomorrow",
    "a few good man",
    "happy day",
    "good morning"
]

In [3]:
cvec = CountVectorizer()

In [4]:
X = cvec.fit_transform(text)
X

<4x8 sparse matrix of type '<class 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [5]:
import pandas as pd
pd.DataFrame(X.toarray(), columns=cvec.get_feature_names())

better  day  few  good  happy  man  morning  tomorrow
0       1    0    0     0      0    0        0         1
1       0    0    1     1      0    1        0         0
2       0    1    0     0      1    0        0         0
3       0    0    0     1      0    0        1         0

In [7]:
import numpy as np

In [9]:
X = np.array([
    [np.nan, 0, 5],
    [4, 8, 9],
    [3,6,3],
    [5, np.nan, 8],
    [9, 5, 0]
])
y = np.array([16, 14, 8, -3, -1])

In [10]:
from sklearn.impute import SimpleImputer

In [11]:
imputer = SimpleImputer(strategy="mean")

In [12]:
X2 = imputer.fit_transform(X)
X2

array([[5.25, 0.  , 5.  ],
       [4.  , 8.  , 9.  ],
       [3.  , 6.  , 3.  ],
       [5.  , 4.75, 8.  ],
       [9.  , 5.  , 0.  ]])

In [13]:
from sklearn.preprocessing import PolynomialFeatures

In [14]:
from sklearn.linear_model import LinearRegression

In [18]:
from sklearn.pipeline import make_pipeline
pl = make_pipeline(SimpleImputer(strategy="mean"),
                   PolynomialFeatures(degree=2),
                   LinearRegression())


In [19]:

pl.fit(X, y)

Pipeline(steps=[('simpleimputer', SimpleImputer()),
                ('polynomialfeatures', PolynomialFeatures()),
                ('linearregression', LinearRegression())])

In [20]:
print(y)

[16 14  8 -3 -1]


In [21]:
print(pl.predict(X))

[16. 14.  8. -3. -1.]
