In [1]:
import tensorflow as tf
import numpy as np

In [3]:
a = tf.constant(2.0)
a

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [4]:
 a.numpy()

2.0

In [7]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [8]:
a.shape

TensorShape([])

In [9]:
type(a.shape)

tensorflow.python.framework.tensor_shape.TensorShape

In [10]:
b = tf.constant([2.0])
b.numpy()

array([2.], dtype=float32)

In [11]:
a = tf.constant(4)
b = tf.constant([4])
a, b

(<tf.Tensor: shape=(), dtype=int32, numpy=4>,
 <tf.Tensor: shape=(1,), dtype=int32, numpy=array([4])>)

In [12]:
b.shape

TensorShape([1])

In [13]:
b.shape[0]

1

In [14]:
c = tf.constant([2,3,4])
c

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4])>

In [16]:
m = tf.constant([ [1,2], [3,4], [5,6] ])
m

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [18]:
m = tf.constant([ [1,2], [3,4], [5,6.] ])
m

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)>