In [1]:
import tensorflow as tf
import numpy as np

In [5]:
x = tf.constant([3,4,5])
y = tf.constant([6,7,8])

In [6]:
x+y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 11, 13])>

In [10]:

print(x+y)

tf.add(x, y)

tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 11, 13])>

In [8]:
a = tf.constant([ [1,2],
                  [3,4] ])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 11, 13])>

In [16]:
b = tf.zeros(4)
b

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>

In [18]:
c = tf.zeros( [2,2])
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [21]:
d = tf.zeros( [3,2,2])
d

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]], dtype=float32)>

In [23]:
d.shape

TensorShape([3, 2, 2])

In [24]:
a.shape

TensorShape([2, 2])

In [25]:
x.shape

TensorShape([3])

In [36]:
w = tf.Variable(1.0)
# 빈값, 초기값 설정가능, Varialbe은 변경이 쉬움
w

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>

In [39]:
w.numpy()

1.0

In [41]:
w.assign(2)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=2.0>

In [42]:
w.numpy()

2.0